### ISSUE TITLE
Minor visual "bugs": FAQs, background & schedule table overflow

### ISSUE THREAD

**Issue by VirtualDOMinic** [rachelnabors/women-of-react-website#6]
Hi. Love the website! I noticed three small UI bugs so thought I'd list them here. I would make a PR but I'm currently unwell and don't have the energy to sort out some local `.gitconfig` issues I'd have to address first, so I'm listing them with my proposed solutions.

## `FrequentlyAskedQuestions` heading overflows on narrow screens
E.g. Huawei P30 (default settings) on chrome, or "iPhone 5/SE" in the inspector of the latest Chrome (macOS).
**Proposed solution**: `overflow-wrap: break-word` on `h2` elements

## Background appears twice
This is especially visible on mobile view, if you scroll to the bottom of the site. 
**Proposed solution**: remove the `background` and `padding` from the `html` element, keep it on `body`.

## Table overflows in "schedule" section on narrow screens
E.g. "iPhone 5/SE" in the inspector of the latest Chrome (macOS). This problem is much less pronounced if the extra padding applied to the `html` is removed (see "background appears twice") 
**Proposed solution**: Either: a) media query to reduce the `padding` of `section` elements below certain resolutions. b) `overflow-x: scroll` on `section` elements

**Comment by SaraVieira** [comment]
Wow!

Thank you so much for the proposed solutions, I will try to get on that today :)
